name: allengayCx Gin Juice

# Controls when the workflow will run
on:
  #pull_request:
  #  types: [opened, reopened, synchronize]
  #  branches: [ "main" ]
  #push: 
  #    branches:
  #    - main
  workflow_dispatch: # *** this adds a run button ***

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Create Output folder
      run: sudo mkdir ${{ github.workspace }}/output/report
    #- name: change owner
    #  run: sudo chown -R 1000:1000 ${{ github.workspace }}/output
    # Scan
    - name: Checkmarx DAST Github Action
      uses: Checkmarx/dast-github-action@v1.0.4
      env:
        CX_APIKEY: ${{ secrets.CX_APIKEY }}
      with:
        command: "web"
        config: './gin_juice.yaml'
        # openapi: file here
        base_url: "https://deu.ast.checkmarx.net" #"https://ast.checkmarx.net"
        environment_id: "7ed62b34-898b-409f-91ff-a1a9d74bdef4" #"2f776f4a-dfda-46d1-9fda-b879307d9b76"
        fail_on: "high"
        verbose: true
        output: ${{ github.workspace }}/output/report
    - name: Reclaim output directory  
      if: always()  
      run: sudo chown -R 1001:1001 ${{ github.workspace }}/output/report
    - uses: actions/upload-artifact@v3
      if: always()
      name: Upload Logs
      with:
        name: report
        path: ${{ github.workspace }}/output/report
