name: Sean Casey brings the thunder.

 

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    name: DAST Casey Express CHOO CHOO
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create Output folder
        run: mkdir ${{ github.workspace }}/output
      - name: Change dir owner
        run: sudo chown -R 1000:1000 ${{ github.workspace }}
      #- name: ls dirs
      #  run: ls -larh ${{ github.workspace }}
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v1.0.4
        env:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
        with:
          command: web
          config: ${{ github.workspace }}/altoro_mutual_dast_scan.yaml
          environment_id: d844fb87-4ae2-43eb-9649-d9e79b13acec
          fail_on: "HIGH"
          log_level: info
          base_url: https://deu.ast.checkmarx.net
          verbose: true
          output: ${{ github.workspace }}/output
      - name: Change dir owner back to gh user
        if: always()
        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output
      - uses: actions/upload-artifact@v3
        if: always()
        name: Upload Logs
        with:
          name: report
          path: ${{ github.workspace }}/output
